#ifndef GAME_HPP
#define GAME_HPP

enum RESET_REASON {
  RESET_NONE = 0,
  RESET_GAME_START,
  RESET_SCORE_MYTEAM,
  RESET_SCORE_OPPONENT,
  RESET_GAME_END,
  RESET_DEADLOCK,
  RESET_GOALKICK,
  RESET_CORNERKICK,
  RESET_PENALTYKICK,
  RESET_HALFTIME,
  RESET_EPISODE_END
};

enum GAME_STATE {
  STATE_DEFAULT = 0,
  STATE_KICKOFF,
  STATE_GOALKICK,
  STATE_CORNERKICK,
  STATE_PENALTYKICK
};

#endif // GAME_HPP
